language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
sudo: required

before_install:
  - sudo apt-get build-dep python-scipy
  - pip install numpy==1.12.1
  - pip install scipy==0.19.0
  - pip install scikit-learn==0.18.1

install:
  - pip install -r requirements.txt
  - python setup.py -q install
# command to run tests
script: pytest