language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install numpy==1.12.1
  - pip install scipy
  - pip install scikit-learn==0.18.1
  - pip install -r requirements.txt
  - python setup.py -q install
# command to run tests
script: pytest